#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and hi for the 9th iteration
i=1
while ((i<11))
do
	if ((i==9))
	then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	((i+=1))
done
