#!/usr/bin/env bash
# This script is displaying "Best School" 8 times and bad luck for 4 and good luck for 8
i=1
while ((i<=10))
do
	if ((i==4))
	then
		echo "bad luck"
	elif ((i==9))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
