#!/usr/bin/env bash
: 'This script is displaying displays 4 and then bad luck from China for the 4th loop iteration
displays 9 and then bad luck from Japan for the 9th loop iteration displays 17 and then bad luck from Italy'
i=1
while ((i<=20))
do
	case $i in
	4)
		echo -e "$i\bad luck from China"
	;;
	9)
		echo -e "$i\nbad luck from Japan"
	;;
	17)
		echo -e "$i\nbad luck from Italy"
	;;
	*)
		echo $i
	;;
	esac
	((i+=1))
done
