#!/usr/bin/env bash
# check if school file exists
school=./school
if [ -e $school ]
then
	echo "school file exists"
	if [ -s $school ]
	then
		echo "school file is not empty"
	elif
		echo "school file is empty"
	fi
	if [ -f $school ] 
	then 
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
