#!/usr/bin/env bash
# Script that creates and deletes files and shows output according to signal
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
trap 'rm /var/run/myscript.pid; exit' SIGQUIT
while :
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
done

